### ISSUE TITLE
Named capture groups in regular expression tests

### ISSUE THREAD

**Issue by jordwest** [jordwest/xexpressions#6]
Currently the 'Examples' unit testing feature only tests whether the regular expression matches on the text as a whole. It should be possible to test the output of capture groups too. Example

```
Test:
  Match: 2015-01-05
    Year: 2015
    Month: 01
    Day: 05
```
